#!/bin/sh
color8=$(xrdb -query | grep 'color8:' | awk '{ print $2 }')
color6=$(xrdb -query | grep 'color6:' | awk 'NR==1 { print $2 }')

#/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
sxhkd &
synclient TapButton1=1 TapButton2=3 TapButton3=2 &
xrdb -merge ~/.Xresources
~/bin/hashwall -f "#3b4457" -b "#232731" -s 4  -r 7 &
compton &
xset fp+ ~/.local/share/fonts &
xset fp rehash &
~/bin/bar &


bspc monitor eDP1 -d  I II III IV 

bspc config border_width            8
bspc config window_gap              8

bspc config split_ratio             0.50
bspc config top_padding             28
bspc config auto_cancel             true
bspc config focus_follows_pointer   true
bspc config auto_alternate          true
bspc config center_pseudo_tiled 	true
bspc config normal_border_color		"$color8"
bspc config focused_border_color	"$color6"
bspc rule -a imv state=floating border=off rectangle=250x250+8+36


wait
