#!/bin/bash
#

bg=#111625
fg=#babcc8

blk=#000000
red=#dd5030
grn=#6cbd3a
ylw=#e6d72d
blu=#2670fc
mag=#f258b9
cyn=#38b2da
wht=#bbbbbb

bblk=#555555
bred=#e17f64
bgrn=#7fba5a
bylw=#ffff55
bblu=#5d8ff3
bmag=#fa83c0
bcyn=#78cee7
bwht=#ffffff

acc=$red
