#!/bin/sh

. /home/daniel/.cache/wal/colors.sh

inactive=$color0
active=$color6

if ! pgrep -x "sxhkd" > /dev/null; then
  sxhkd &
fi

xrdb -merge ~/.Xresources

if ! pgrep -x "compton" > /dev/null; then
  compton &
fi

xset fp+ ~/dots/local/.local/share/fonts &
xset fp+ ~/.local/share/fonts/bitmap-font-collections &
xset fp rehash &

pkill -x lemonbar &
lpanel &

. ~/.fehbg &

bspc monitor eDP-1 -d  I II III IV

bspc config border_width            4
bspc config window_gap              4

bspc config split_ratio             0.50
bspc config bottom_padding          0
bspc config top_padding             24
bspc config focus_follows_pointer   true
bspc config center_pseudo_tiled     true
bspc config normal_border_color	    "$inactive"
bspc config focused_border_color    "$active"
bspc config presel_feedback_color   "$active"

bspc rule -a Google-chrome-stable state=floating rectangle=720x400+323+184

wait
