#!/bin/sh
inactive=$(xrq 'color8')
active=$(xrq 'color1')
if ! pgrep -x "sxhkd" > /dev/null; then
  sxhkd &
fi

xrdb -merge ~/.Xresources

if ! pgrep -x "compton" > /dev/null; then
  compton &
fi

xset fp+ ~/.local/share/fonts &
xset fp rehash &

if ! pgrep -x "lemonbar" > /dev/null; then
  ~/bin/lpanel &
fi

. ~/.fehbg &

urxvtd &
xfsettingsd &

bspc monitor eDP-1 -d  I II III IV

bspc config border_width            4
bspc config window_gap              4

bspc config split_ratio             0.50
bspc config top_padding             28
bspc config focus_follows_pointer   true
bspc config center_pseudo_tiled     true
bspc config normal_border_color	    "$inactive"
bspc config focused_border_color    "$active"
bspc config presel_feedback_color   "$active"
bspc rule -a imv state=floating border=off rectangle=250x250+8+36


wait
