#!/bin/bash 

bg=#232325
fg=#e6e6e6

blk=#232325
bblk=#232325

red=#fc419f
bred=#fc419f

grn=#21ffce
bgrn=#22ffce

ylw=#ffffa0
bylw=#f1fa8c

blu=#4c45cd
bblu=#4c45cd

mag=#0a60ff
bmag=#0a60ff

cyn=#54ffff
bcyn=#54ffff

wht=#bbbbbb
bwht=#ffffff

acc=$red
