#!/bin/bash
#

bg=#111c2a
fg=#ffffff

blk=#0c151e
red=#f82939
grn=#3beb2a
ylw=#fcc146
blu=#2d4562
mag=#6f4ebc
cyn=#63cce3
wht=#838c95

bblk=#454640
bred=#f82939
bgrn=#3beb2a
bylw=#fcc146
bblu=#2d4562
bmag=#6f4ebc
bcyn=#63cce3
bwht=#ffffff

acc=$mag
